# Generated by Django 2.1.5 on 2019-03-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('token_symbol', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=150)),
                ('telegram_contact', models.CharField(max_length=150)),
                ('facebook', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('reddit', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
            ],
        ),
    ]
