# Generated by Django 2.1.5 on 2019-03-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_packageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
