# Generated by Django 2.1.5 on 2019-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190321_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
